spring:
  profiles:
    active: vault

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8888

logging:
  level:
    root: info