version: '3.7'

services:
  vault:
    image: vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
      - ./policies:/vault/policies
    networks:
      - vault-dev
    entrypoint: vault server -config=/vault/config/dev-file.hcl
    restart: always

networks:
  vault-dev: