spring:
  datasource:
    name: client-db
    username: client-user
    # password is client-password
    # provide sample-password as jasypt.encryptor.password to decrypt
    password: ENC(A+eOm8o7/iYmYVrqrbpxf0eGTJywpR5f)
  h2:
    console:
      enabled: true
  application:
    name: local-client

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
